namespace FinalInferno {
    public enum StatusEffectVisuals {
        Null = 0,// Esses valores serão usados para acesso numa array, então precisam começar em 0 e incrementar de 1 em 1
        Bribed = 1,
        Confused = 2,
        DamageDown = 3,
        DamageDownExponential = 4,
        DamageDrained = 5,
        DamageUp = 6,
        DamageUpExponential = 7,
        DefenseUp = 8,
        DefenseDown = 9,
        Burn = 10,
        Hypothermia = 11,
        Quicksand = 12,
        Suffocation = 13,
        DamageOverTime = 14,
        DelayedSkill = 15,
        DrainingDamage = 16,
        HealingOverTime = 17,
        Hiding = 18,
        LosingHPOverTime = 19,
        MarketCrash = 20,
        Paralyzed = 21,
        Regenerating = 22,
        ResistanceDown = 23,
        ResistanceUp = 24,
        SpeedDown = 25,
        SpeedUp = 26,
        StatusResistUp = 27,
        Taunting = 28,
        VengefulGhost = 29,
        Defending = 30,
        SpeedDrained = 31,
        DrainingSpeed = 32,
    }
}
